parameters:
#    rohea_open_x_client.example.class: Rohea\OpenXClientBundle\Example

services:
    rohea_open_x_integration.api_client_factory:
        class: Rohea\OpenXIntegrationBundle\Service\ApiClientFactory
        arguments: [%rohea_open_x_integration.servers%]
